name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            macayaven/backend-core:latest
            macayaven/backend-core:${{ github.sha }}
          cache-from: type=registry,ref=macayaven/backend-core:buildcache
          cache-to: type=registry,ref=macayaven/backend-core:buildcache,mode=max

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/backend-core
            docker pull macayaven/backend-core:${{ github.sha }}
            docker compose down
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            docker compose up -d
            docker system prune -f
