name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Process Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push Release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            macayaven/backend-core:${{ steps.version.outputs.VERSION }}
          cache-from: type=registry,ref=macayaven/backend-core:buildcache
          cache-to: type=registry,ref=macayaven/backend-core:buildcache,mode=max

      - name: Create Release Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CHANGELOG.md
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
